"""change medicines to array

Revision ID: 81eaf9fa31bc
Revises: 42fb7eac9ff4
Create Date: 2026-06-22 21:35:34.281158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81eaf9fa31bc'
down_revision: Union[str, Sequence[str], None] = '42fb7eac9ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
